- name: Add user admin with sudo privileges and SSH access
  hosts: all
  become: true
  tasks:
    - name: Add the user admin
      ansible.builtin.user:
        name: admin
        shell: /bin/bash
        groups: sudo
        state: present

    - name: Add public SSH key for admin
      ansible.posix.authorized_key:
        user: admin
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        path: /home/admin/.ssh/authorized_keys

    - name: Enable no password sudo for admin
      ansible.builtin.copy:
        dest: /etc/sudoers.d/admin
        content: "admin ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: "0440"
